Feature/update home page
GoodBot-Society/responsible-tech-repo pull request #34
Opened 2024-12-19 05:14 UTC by Unknown-0perator

2024-12-22 22:39 UTC, CorreyL requested changes
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/c20cbccf-ed97-47f8-acff-c86d7c49055f" />

Just noting that during my review, I tried to run this application locally, but seem to need local config values I haven't been informed of

2024-12-22 22:39 UTC, CorreyL commented on app/comps/HomePage.client.jsx
> +            "Responsible Tech and AI Education and Capacity"],
There seems to be an unnecessary mixing of double quotes `"` and single quotes here `'`

2024-12-22 22:39 UTC, CorreyL commented on app/comps/HomePage.client.jsx
> +    const [selectedSubCategory, setSelectedSubCategory] = useState("All");
Instead of hard-coding this string value, and checking its equivalency in the JSX as done below, such as:

```javascript
<SubCategoryTab label="All" setSelectedSubCategory={setSelectedSubCategory} isSelected={selectedSubCategory === "All"} />
```

I would make this string a constant, in-case it ever needs to get changed in the future, so something like:

```
const ALL_SUBCATEGORIES = 'All';

// ...

const [selectedSubCategory, setSelectedSubCategory] = useState(ALL_SUBCATEGORIES);

// ...

<SubCategoryTab label="All" setSelectedSubCategory={setSelectedSubCategory} isSelected={selectedSubCategory === ALL_SUBCATEGORIES} />
```

This is to reduce the number of hard-coded values spread throughout the code.

2024-12-22 22:39 UTC, CorreyL commented on app/layout.js
> +          {/* @todo - refactor this into  SiteHeader component*/}
Seems like with the implementation of the new `Header` component, this `@todo` can be removed?

2024-12-22 22:39 UTC, CorreyL commented on app/layout.js
> +            <Footer></Footer>
```suggestion
            <Footer/>
```

2024-12-22 22:39 UTC, CorreyL commented on app/layout.js
> +    </html >
```suggestion
      </body>
    </html>
```

Seems like an unnecessary introduction of spaces that other components don't have?

2024-12-22 22:39 UTC, CorreyL commented on app/page.js
> +    console.log(error);
Not really sure what is considered idiomatic for this codebase, but if there's by any chance better error-handling logic implemented elsewhere (i.e. logging the error to a server for debugging purposes?), then we should consider that, instead of just `console.log`ing

2024-12-22 22:39 UTC, CorreyL commented on app/page.js
> +    return cards;
```suggestion
    return await cardsHome(artifact);
```

2024-12-22 22:39 UTC, CorreyL commented on components/Header.jsx
> +      <h1 className="text-base font-bold font-poppins text-center text-[#242424]">Responsible Tech Repo</h1>
If `#242424` is an explicit color chosen by a design team, I wonder if we should consolidate this to a CSS class, and reference that CSS class, rather than "hard-coding" `text-[#242424]` throughout the codebase?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/Card.jsx
> +            </div> */}
```suggestion
```

If this is no longer needed, I reckon it can be deleted?

If it's going to be used for a future purpose, perhaps putting a todo here, or alternatively uncommenting it but setting the `hidden: true` CSS property, with a small todo above, would be better?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/CategoryTab.jsx
> +        setSelectedSubCategory('All')
If you take my suggestion about the `ALL_SUBCATEGORY` point above, reference that same variable here

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/FilterDropdown.jsx
> +        options: ['business', 'comp science', 'engineering', 'government', 'law']
Feels like these options should be capitalized, and also `comp science` should be `Computer Science`?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/FilterDropdown.jsx
> +        options: ['artificial intelligence', 'privacy', 'data integrity', 'bills', 'personal information']
Feels like this should also be capitalized

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/FilterDropdown.jsx
> +                            ))}
I like the idea here behind consolidating repetitive data-structures into something that is iterable, but I wonder if rather than having to conditionally render JSX based on an arbitrary `type` key, you could abstract the resulting JSX into two separate components

```
const Checkbox = (options) => {
  return (
    <label key={i} className="flex gap-4 items-center mt-2">
        <input type="checkbox" className="accent-black" />
        {options}
    </label>
  );
};

// Do something similar for Radio
```

Then just put those options into two separate variables

```
const checkboxOptions = [
  {
    title: "CONTENT TYPE",
    options: ['Magazine Article', 'Web Resource', 'Conference Proceeding', 'Journal Article', 'Newspaper Article'],
  },
  // ...
]

// ...

return (
  // ...
  {checkboxOptions.map((checkboxOption) => <Checkbox option={checkboxoption}/>)}
)
```

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/OrganizationCard.jsx
> +                <div className="text-sm px-9 py-3 bg-[#D9D9D9]">Logo</div>
Just calling out another instance of a "hard-coded" color that might be better to be consolidated as a CSS class/variable, and referencing that CSS class/variable instead?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/OrganizationCard.jsx
> +                <p className="text-sm text-[#1daeef]"></p>
Just calling out another instance of a "hard-coded" color that might be better to be consolidated as a CSS class/variable, and referencing that CSS class/variable instead?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/Search.jsx
> +      <input type="text" placeholder="Search Goodbot ex. Digital Charter Canada" className="w-full shadow-sm border border-[#A1A1A1] rounded-md px-3 py-1.5 text-sm" />
Just calling out another instance of a "hard-coded" color that might be better to be consolidated as a CSS class/variable, and referencing that CSS class/variable instead?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/Search.jsx
> +      <button className="shadow text-base font-bold uppercase flex items-center justify-center gap-2 bg-[#A3E2EC] px-2 py-2.5 rounded-md min-w-[116px]"><SearchIcon size={20} />search</button>
Just calling out another instance of a "hard-coded" color that might be better to be consolidated as a CSS class/variable, and referencing that CSS class/variable instead?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/SeeLessButton.jsx
> +            <button className="shadow text-base font-bold uppercase flex items-center justify-center gap-2 bg-[#A3E2EC] px-2 py-2.5 rounded-md min-w-[116px] hover:bg-[#95dbe6]"><SearchIcon size={20}
Just calling out another instance of a "hard-coded" color that might be better to be consolidated as a CSS class/variable, and referencing that CSS class/variable instead?

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/SubCategoryTab.jsx
> +        <p className={(isSelected) ? "subcategory-btn subcategory-btn--active" : "subcategory-btn"} onClick={() => handleSubCategoryClick(label)}>{label}</p>
```suggestion
        <p className={`subcategory-btn ${isSelected ? 'subcategory-btn--active' : ''}`} onClick={() => handleSubCategoryClick(label)}>{label}</p>
```

2024-12-22 22:39 UTC, CorreyL commented on components/home-page-ui/TopVoiceCard.jsx
More hard-coded CSS colors in here

2025-01-21 03:55 UTC, Unknown-0perator commented on app/comps/HomePage.client.jsx
> +            "Responsible Tech and AI Education and Capacity"],
[36ccad5](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/36ccad5370a2a2f3fd5349a56e67fb957195d590)

2025-01-29 01:15 UTC, Unknown-0perator commented on components/home-page-ui/Card.jsx
> +            </div> */}
addressed in [00191b1](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/00191b1720f532b816bee67c3046c9a00ac0ff01)

2025-01-29 01:22 UTC, Unknown-0perator commented on components/home-page-ui/CategoryTab.jsx
> +        setSelectedSubCategory('All')
addressed [d1dcca4](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/d1dcca40629a4ca18f2f073bda8ff2d3c6d6302d)

2025-01-29 01:28 UTC, Unknown-0perator commented on components/home-page-ui/FilterDropdown.jsx
> +        options: ['business', 'comp science', 'engineering', 'government', 'law']
Addressed [49b330a](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/49b330a7ee79af8dd89f14a5e52765e0a6f1a130), [f193afa](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/f193afa1b56a7ebf0cb5992c1414709d5ee2e4e0)

2025-01-29 01:28 UTC, Unknown-0perator commented on components/home-page-ui/FilterDropdown.jsx
> +        options: ['artificial intelligence', 'privacy', 'data integrity', 'bills', 'personal information']
Addressed [49b330a](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/49b330a7ee79af8dd89f14a5e52765e0a6f1a130)

2025-01-29 01:30 UTC, Unknown-0perator commented on app/layout.js
> +          {/* @todo - refactor this into  SiteHeader component*/}
addressed [536876b](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/536876b926c9e010572c3e7f687d81cfffc0c40a)

2025-01-29 01:32 UTC, Unknown-0perator commented on app/comps/HomePage.client.jsx
> +    const [selectedSubCategory, setSelectedSubCategory] = useState("All");
[e8c8baa](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/e8c8baa247d76852b18e5e46009704af1a7cca63)

2025-01-29 01:45 UTC, Unknown-0perator commented on components/Header.jsx
> +      <h1 className="text-base font-bold font-poppins text-center text-[#242424]">Responsible Tech Repo</h1>
[696dfb5](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/696dfb5881d7d86c5f54c4e20d469b2bc9d1847c)

2025-01-30 01:35 UTC, Unknown-0perator commented on components/home-page-ui/FilterDropdown.jsx
> +                            ))}
[fa92886](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/fa92886bcb7d2887fa3e34f91e87c20d2bb77655)

2025-01-30 01:44 UTC, Unknown-0perator commented on app/page.js
> +    console.log(error);
I am thinking to create a error message component for better error handling in front end but I will discuss it with UXUI team to ensure it aligns with overall design

2025-02-06 03:14 UTC, CorreyL requested changes
![image](https://github.com/user-attachments/assets/ef938b7c-abe9-4221-afdb-c6a28947eaab)

I noticed the previous implementation of the website (currently on `main`) had a toggle for `Light`, `Dark` and `System` mode.

The current implementation seems to have a very low [contrast ratio](https://en.wikipedia.org/wiki/Contrast_ratio) that makes a lot of the text on the page difficult or impossible to read:

![image](https://github.com/user-attachments/assets/99d26589-89b7-406f-80fc-efeeaee083f2)

I'm wondering if CSS adjustments need to made such that we are only rendering in Light Mode, or we take into account that this site supports Dark Mode, and have CSS classes for it accordingly?

To confirm my assumption, when I render the site in a browser that is set to `Light` mode, all text appears to be legible:

![image](https://github.com/user-attachments/assets/18d44bf4-ff36-463d-994b-3227bdd11d41)

2025-02-06 03:14 UTC, CorreyL commented on app/comps/HomePage.client.jsx
Unless, I'm missing something, `comps` seem to have been a short form for `components`?

I wonder if we should just move this (the only file in this directory now) into the `components/` folder?

2025-02-19 02:30 UTC, CorreyL reviewed
My understanding from Renee is that there is hope to push this out to Production asap.

If it is agreed upon with the relevant stakeholders that it is a design focused release to go out (and there are no users relying on the actual functionality of the Search capabilities, Preview capabilities, or any expectation that the Policies are clickable), then this seems like an iterative step in the right direction.

As part of my comments below, please note that that many of the buttons and links are non-functional at the moment. If this is NOT the agreed upon state of the website that we want to release, then I would hold off, and iterate on this branch further.

Furthermore, please note that this review is based on a Supabase URL ending in `dnc` and a key starting with `ey` and ending with `8U`.

If there is a separate Production Supabase key that this should be tested against, please note that I was not provided any other keys to verify functionality with.

2025-02-19 02:30 UTC, CorreyL commented on components/Header.jsx
> +      </Link>
Might be worth hiding this element for now if the `/login` page doesn't exist at the moment?

![image](https://github.com/user-attachments/assets/6370ad15-ba1f-42f6-b22b-c321de26dbc4)

2025-02-19 02:30 UTC, CorreyL commented on app/about/page.jsx
There's a few errors in the console when you first open up `localhost:3000` that might be worth fixing up before pushing to Production

![image](https://github.com/user-attachments/assets/a8a59ff1-b90b-45cd-b6bc-331d44218982)
![image](https://github.com/user-attachments/assets/3847bc29-56ee-44ae-aa8e-fe102077f908)

2025-02-19 02:30 UTC, CorreyL commented on app/comps/HomePage.client.jsx
> +                        {selectedCategory.sub_categories.map((subCategory) => (
Is it intentional at the moment that choosing a Sub-Category does not change any subsequent content below it?

![image](https://github.com/user-attachments/assets/bf383c71-75b0-4d78-9b0d-b83da7bc992f)

![image](https://github.com/user-attachments/assets/2ef98bfb-9c9c-4543-aee2-10018ccbf1fd)

Notice how me choosing `Disinformation & Deepfakes` and `Attention, Mental Health & Well Being` doesn't seem to change any of the `Community`, or `Legislation` content below it.

All good if this is intentional, and perhaps just part of the iterative development process, I'd just like to confirm.

2025-02-19 02:30 UTC, CorreyL commented on components/Footer.jsx
> +                <button className="min-w-[224px] py-[18px] bg-sky-900 text-base text-white rounded-[30px] mb-[50px]">Contact Us</button>
Just calling out that this button, and all the social buttons, don't seem to be functional at the moment.

If the goal is to just meet the Design requirements, and we will iterate on this further in the future, then that's okay

![image](https://github.com/user-attachments/assets/e683ad5f-7071-4065-995c-6866d8ab5556)

2025-02-19 02:30 UTC, CorreyL commented on app/comps/HomePage.client.jsx
> +                        {selectedCategory.sub_categories.map((subCategory) => (
I'd also like to note that all the areas where images seem like they _should_ be are all just grey boxes.

Again, this could just be an iterative development step, and those will be filled in later. If that is all intentional, then that is okay for now.

2025-02-19 02:30 UTC, CorreyL commented on components/home-page-ui/Search.jsx
> +      <button className="shadow text-base font-bold uppercase flex items-center justify-center gap-2 bg-[var(--button-primary)] px-2 py-2.5 rounded-md min-w-[116px]"><SearchIcon size={20} />search</b
Just calling out that trying to search something, like `Digital Charter Canada`, and clicking the `Search` button, or pressing `Enter`, does not actual fire off a search, and just seems to re-direct to the home page again

![image](https://github.com/user-attachments/assets/b287bea3-5c6d-41f0-b874-537f4ca1254f)

If this is intentional, then this is okay for now, but I want to note that this functionality seemed to work okay in the `main` branch:

![image](https://github.com/user-attachments/assets/3854c9a9-974c-45d0-bb70-965c6c9ae8e2)

2025-02-19 03:12 UTC, Unknown-0perator commented on app/about/page.jsx
[ca9dbc6](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/ca9dbc64dcf1c5c51dac304c312653ad2d776a69)

2025-02-19 03:22 UTC, Unknown-0perator commented on components/Header.jsx
> +      </Link>
[3d27e3c](https://github.com/gogoodbot/responsible-tech-repo/pull/34/commits/3d27e3c96e004bfa0420e97eaf7bdec04bed0bbd)

2025-02-19 03:31 UTC, Unknown-0perator commented on components/home-page-ui/Search.jsx
> +      <button className="shadow text-base font-bold uppercase flex items-center justify-center gap-2 bg-[var(--button-primary)] px-2 py-2.5 rounded-md min-w-[116px]"><SearchIcon size={20} />search</b
Thanks @CorreyL ,
There is new design for search page that I may implement later in different branch
[Figma](https://www.figma.com/design/5ki9Mi8uAMgYTLaG2QThtU/Goodbot-%5C-Responsible-Tech-Repo-OFFICIAL?node-id=3412-6289&t=wIW2oumT5lBfkA8V-0)

2025-02-20 01:47 UTC, CorreyL reviewed
I provided a link to the Vercel Preview page to Renee:

https://goodbot-git-feature-updatehome-page-goodbot.vercel.app/

If they or another relevant Goodbot stakeholder (including yourself Ahmad, if you give the approval that this is indeed what the Goodbot team has agreed upon) give the green light on the current state of the application in this branch, then I will also provide my approval!

As it stands, it hasn't been clearly communicated to me if it is the goal of this PR to ship a non-functional but design matching implementation of the Figma.

2025-02-20 03:32 UTC, Unknown-0perator commented
Thanks, @CorreyL, for the review and the important points.
I discussed the issue with Fauwail and Renee, and I got approval for the current state of the application in this branch to go live.

2025-02-20 04:36 UTC, CorreyL approved these changes
> Thanks, @CorreyL, for the review and the important points. I discussed the issue with Fauwail and Renee, and I got approval for the current state of the application in this branch to go live.

Then this seems good to ship to me in terms of a first iteration!

2025-02-25 02:56 UTC, CorreyL approved these changes
Re-approving based on my comment here, given that there doesn't seem to have been any new commits/changes since my last approval

https://github.com/gogoodbot/responsible-tech-repo/pull/34#pullrequestreview-2628690141

Edit: Ahh, since I don't have `Write` access to the `responsible-tech-repo`, my approval doesn't count

<img width="566" alt="image" src="https://github.com/user-attachments/assets/71e9db4b-a5f2-4df3-a16b-51931f8e4d68" />

2025-02-28 03:58 UTC, Unknown-0perator commented
As we discussed in the meeting, I am going to close this PR. There will be a develop branch, and any new feature will be created against it.

2025-02-28 16:30 UTC, CorreyL commented
@Unknown-0perator To keep all the conversations & changes within one PR, when the `develop` branch is created, we can just edit this existing PR to point to the new `develop` branch

2025-03-11 00:59 UTC, merged